### ISSUE TITLE
QSI 500 driver image assembly error

### ISSUE THREAD

**Issue by Chandler** [indigo-astronomy/indigo#114]
When using Astroimager on macOS 10.13.6 with a QSI 583 camera, the image is not correctly reassembled. It is displayed with the left half on the right and vice versa. 

The driver in use is INDIGO QSI 500 2.0.0.2

Please let me know if you think this could be caused somewhere else other than the driver (camera, Astroimager, OS).

<img width="1440" alt="screen shot 2018-12-23 at 12 12 21 am" src="https://user-images.githubusercontent.com/55420/50381922-aa3bc800-0647-11e9-9a1c-0c671bbc05ed.png">

**Comment by Chandler** [comment]
I'm not sure how to update Astroimager to get the lastest driver or an easy way to test this out using the INDIGO driver directly.

**Comment by polakovic** [comment]
I'll look at it. Does it happen only with the preview or also with the capture?

This is the most recent AstroImager: 
http://download.cloudmakers.eu/AstroImager_3.9_420.dmg

And you can also build and run INDIGO from source and run indigo_server with indigo_ccd_qsi driver, AstroImage will find it.

**Comment by Chandler** [comment]
It also happens with the capture, I tried the updated Astroimager and am seeing the same issue. I will try playing with the INDIGO source build (I see a few changes were made in the last month or so to the QSI driver.

https://github.com/indigo-astronomy/indigo/commit/945b9de9647b78c51435beff5c6f81f61cac70bc

**Comment by polakovic** [comment]
The only important change is line 194. If you can build it from source, pls. can you try to change first true to false?

**Comment by polakovic** [comment]
Sorry, this is not the issue, keep it. The problem is, that PRIVATE_DATA->buffer is pointer to short, while FITS_HEADER_SIZE is in bytes. I'll fix it and build new AstroImager in a few minutes...

**Comment by Chandler** [comment]
thanks for the quick response!

**Comment by polakovic** [comment]
Pls. can you try this one?

http://download.cloudmakers.eu/AstroImager_3.9_421.dmg

**Comment by Chandler** [comment]
It works!! thank you!

<img width="1033" alt="screen shot 2018-12-23 at 1 07 25 am" src="https://user-images.githubusercontent.com/55420/50382220-24bc1600-064f-11e9-8fa8-081bbc47c762.png">

**Comment by polakovic** [comment]
Great! Thank you very much, you helped us a lot.

**Comment by polakovic** [comment]
P.S. I see you used AstroImager from AppStore. In this case you need to "register" it first (in AstroImager > Register) to create permanent license allowing you to run copies downloaded directly from our web.
