### ISSUE TITLE
Mount_synscan interpretes Slew command sometimes as Sync command

### ISSUE THREAD

**Issue by JohanBakk** [indigo-astronomy/indigo#125]
Mount_synscan interpretes a Slew command sometimes as Sync command. Step to reproduce; 

- i selected a star and slewed to it
- next i selected another star at a sizeable distance and pressed sync
- an alignment point is created and the reticle changes position to the last star
- next i selected the original star again and pressed Slew
- in stead of slewing to the star, a second alignment point is created
- the linked video demonstrates this behaviour

[https://www.dropbox.com/s/9siti2mchjn3rw5/Screen%20Recording%202018-12-28%20at%2020.30.23.mov?dl=0](url)

**Comment by polakovic** [comment]
AstroTelescope bug fixed in AT3.9_424
