### ISSUE TITLE
Alignment point precision - using single point alignment with mount_synscan

### ISSUE THREAD

**Issue by JohanBakk** [indigo-astronomy/indigo#127]
When using AT and mount_synscan, i noticed that the RA/DEC values of alignment points are two decimals, where the raw values they are derived from are 4 decimals. Using 4 decimals for alignment points as well would lead to better alignment/pointing precision.

**Comment by polakovic** [comment]
Alignment points coordinates are actually "double" numbers. What you see is just "label" of the property item, but it will be better to show it in full sexagesimal format instead.

**Comment by JohanBakk** [comment]
Maybe it is better to show the label in h:mm:ss format then, so it is easily compared to all other coordinates. The same goes for the RAW Coordinates property.

**Comment by polakovic** [comment]
It will be even more complicated, e.g. side of pier is missing.

**Comment by JohanBakk** [comment]
David added side of pier yesterday. Tested it, works fine.

**Comment by polakovic** [comment]
Yes, I know. It is also added to the alignment point structure, so it needs to be added to the label.

**Comment by polakovic** [comment]
changed to format "h:mm:ss h:mm:ss E/W".
