### ISSUE TITLE
Single point alignment points are lost when the client disconnects

### ISSUE THREAD

**Issue by JohanBakk** [indigo-astronomy/indigo#128]
When using AT and mount_synscan, i noticed that single point alignment points are lost as soon as the client (in this case AT) disconnects from the server. It would be better if they were preserved by the server until the client reconnects or the server is reinitialised/restarted.

**Comment by polakovic** [comment]
This is framework issue. Alignment points are saved only together wiht configuration, what's wrong.

**Comment by polakovic** [comment]
fixed
