### ISSUE TITLE
Mount_synscan enhancement - (de)activate alignment points on alignment mode switch

### ISSUE THREAD

**Issue by JohanBakk** [indigo-astronomy/indigo#138]
When there are multiple alignment points present and the user switches between alignment modes, the alignment point selection remains as is. This means when the user switches from single point to nearest point, in ICP only one alignment point is selected. The other way around, when the user switches from nearest point to single point, all alignments points remain selected. 

Maybe it is better to make it like this;

- when the user switches from single point to nearest point -> select all alignment points
- when the user switches from nearest point to single point -> deselect all but the last alignment point

**Comment by polakovic** [comment]
Done. Single point mode selects last point, nearest point and multi point modes select all points.
