### ISSUE TITLE
Mount_synscan enhancement - assign proper value to Mount model property

### ISSUE THREAD

**Issue by JohanBakk** [indigo-astronomy/indigo#139]
Currently the mount_synscan driver sets the mount model property to "synscan". Since the mount model number enumeration is known and the model can be requested from the mount, it would nicer to set the proper mount model and report this in the connection message at the time of connection.

From the skywatcher documentation:

0 = EQ6 GOTO Series  
1 = HEQ5 GOTO Series  
2 = EQ5 GOTO Series  
3 = EQ3 GOTO Series  
4 = EQ8 GOTO Series  
5 = AZ-EQ6 GOTO Series  
6 = AZ-EQ5 GOTO Series  
128 ~ 143 = AZ GOTO Series  
144 ~ 159 = DOB GOTO Series  
160 = AllView GOTO Series

**Comment by polakovic** [comment]
I suspect it is not possible. This enumeration belongs to NexStar protocol (communication with hand controller) not to SynScan protocol (communication with motor controllers).

**Comment by JohanBakk** [comment]
Tested it, fixed!
