### ISSUE TITLE
indigo_wheel_asi and indigo_ccd_asi error on armv6l build

### ISSUE THREAD

**Issue by asantam** [indigo-astronomy/indigo#164]
The **indigo_wheel_as**i and **indigo_ccd_asi** drivers give an error on the **armv6** built. While the make process works fine and the drivers are compiled, when I try to load them in indigo_server the server just keeps restarting. Moreover, when I run the drivers by themselves (e.g. ./indigo_asi_wheel), they exit with the **"Illegal instruction"** error, something that doesn't happen with other drivers (even If they are not designed to be run by themselves).

Here is the output of the strace: [https://pastebin.com/UEmAQw1M](https://pastebin.com/UEmAQw1M)

Note that this doesn't happen with indigo_focuser_asi which can be loaded fine with indigo_server and doesn't give an error when run by itself. Moreover, both indigo_wheel_asi and indigo_ccd_asi work ok on the x86 build.

Any idea of what may be causing this? 
Thanks

**Comment by polakovic** [comment]
I suspect we use arm7 binaries. Rumen, any idea?

**Comment by asantam** [comment]
You are right, I didn't thought to check.

![image](https://user-images.githubusercontent.com/3071903/52744029-79be3d80-2fa9-11e9-80f4-88e1d7e73103.png).

Good place to start, will try to fix it and submit a PR.

**Comment by rumengb** [comment]
Yes rhis is what we use. We used to use arm6 but you changed it :)

**Comment by asantam** [comment]
Hi Rumen, is there any benefit on using the arm7 ones? Maybe the simplest option is just to go back to the arm6 ones.

**Comment by asantam** [comment]
I replaced libASICamera2.a and libEFWFilter.a with their arm6 version (taken from the ZWO SDK) and now it works perfectly. 

Let me know if it makes sense to you to go back to the arm6 drivers (as arm7 is backwards compatible) so I can make a simple PR or if you prefer to leave a specific driver for each architecture version.  The rest of the arm7 drivers are:

ccd_sbig/bin_externals/sbigudrv/lib/Linux/arm/libsbigudrv.a
guider_asi/bin_externals/libusb2st4conv/lib/Linux/arm/libUSB2ST4Conv.a
ccd_mi/bin_externals/libgxccd/lib/Linux/arm/libgxccd.a

I think all of them have a arm6 version available (at least in the libindi repository).

**Comment by polakovic** [comment]
To be honest, I don't remember why we used arm7 instead of arm6 binaries in some cases, maybe it is my fault :) So pls. make PR if you can test it.

**Comment by asantam** [comment]
Ok, I managed to get all 3 arm6 asi drivers working (wheel, ccd, and guider). However, neither ccd_sbig nor ccd_mi work when I replaced the .a files from the ones in indilib. Because of this I'll limited PR #165 to an asi drivers fix.
