### ISSUE TITLE
Windows Client tweaks needed

### ISSUE THREAD

**Issue by MasterYoddha** [indigo-astronomy/indigo#168]
Hello,

I'm trying to compile the windows client. The project file needs to polished just a bit:

In additional include to use (rather than the full path)
.\externals\pthreads4w\include

And in additional library
.\externals\pthreads4w\lib

Fixing the settings moved to compilation. However there are few errors. See the attached image.

Regards,
Ivo

![clipboard01_g](https://user-images.githubusercontent.com/15908303/53025080-f9944e00-3468-11e9-9272-3cc4f3ca2355.png)

**Comment by polakovic** [comment]
Hm, we replaced gethostbyname() by getaddrinfo() because of better error handling. but getaddrinfo() is not available on windows :( I have to look at it once again, thank you for the report.

**Comment by polakovic** [comment]
Pls. can you try now? I fixed absolute search paths and added one include to fix the issue with getaddrinfo().

**Comment by MasterYoddha** [comment]
Works perfectly! :)

Many thanks!
