### ISSUE TITLE
SSAG/QHY5 VID mismatch?

### ISSUE THREAD

**Issue by garth123** [indigo-astronomy/indigo#181]
My SSAG doesn't show up at all when trying to use it with INDIGO on RPi.

My VID is listed as `16C0:296D` which isn't either of [the two VIDs listed for this SSAG/QHY5 driver](https://github.com/indigo-astronomy/indigo/blob/master/indigo_drivers/ccd_ssag/README.md).

The complete identifier from lsusb is:

`Bus 001 Device 011: ID 16c0:296d Van Ooijen Technische Informatic`

The device isn't recognized at all with the `indigo_ccd_ssag driver`, but is with the `indigo_ccd_qhy` driver (as QHY5M). However, I experience the same operational failures with the INDIGO QHY driver as I do with INDI (like having to eventually physically disconnect/reconnect the device after stopping or aborting an exposure)

Is there any way to get the SSAG driver to acknowledge my device so I can see if it fares any better than the QHY driver?

**Comment by polakovic** [comment]
I added 16c0:296d to SSAG driver.
