### ISSUE TITLE
RGB image conversion (jpg) for color CCDs

### ISSUE THREAD

**Issue by universe241981** [indigo-astronomy/indigo#184]
QHY5P-II-C + Pi0W

Try to capture a light frame and save in jpg format.
The saved jpg file is monochrome.
Anyway to do RGB conversion before save in jpg format?

Thanks.

**Comment by polakovic** [comment]
You're correct. The driver doesn't debayer and QHY SDK neither, so any image produced by any QHY camera is always "raw" and thus JPEG is monochrome. It is sufficient for what is intended purpose of JPEG format in this case - very fast and very approximate preview, usually in web based clients.
