### ISSUE TITLE
PORTS property on linux doesn't show symlinks

### ISSUE THREAD

**Issue by polakovic** [indigo-astronomy/indigo#186]

**Comment by rumengb** [comment]
Will fix it as soon as i can. On vacation now :)

**Comment by rumengb** [comment]
fixed with commits: bd522748e1ca62672f790da0527847256f7f7994 and a24432ca1189df12426d8179dff019e60b304800

**Comment by polakovic** [comment]
Doesn't work :( Duplicate items...

19:54:10.798241 indigo_server: INDIGO Bus: property definition
19:54:10.798263 indigo_server: 'Mount SynScan'.'DEVICE_PORTS' SWITCH rw Ok 2.0 OneOfMany { // Serial ports
19:54:10.798283 indigo_server:   'REFRESH' = Off // Refresh
19:54:10.798303 indigo_server:   '/dev/ttyUSB1' = Off // /dev/ttyUSB1
19:54:10.798323 indigo_server:   '/dev/serial1' = Off // /dev/serial1
19:54:10.798342 indigo_server:   '/dev/ttyAMA0' = Off // /dev/ttyAMA0
19:54:10.798362 indigo_server:   '/dev/ttyUSB1' = Off // /dev/ttyUSB1
19:54:10.798382 indigo_server:   '/dev/ttyUSB0' = Off // /dev/ttyUSB0
19:54:10.798400 indigo_server: }

**Comment by polakovic** [comment]
BTW, symlink (ttyUPB -> ttyUSB0) is missing :)

**Comment by rumengb** [comment]
please post output of:
ls -al /dev
and
ls -al /dev/serial/by-id

**Comment by polakovic** [comment]
PegasusAstro UBP and EQDir is connected

polakovic@raspi32:~/indigo $ lsusb
Bus 001 Device 047: ID 067b:2303 Prolific Technology, Inc. PL2303 Serial Port
Bus 001 Device 046: ID 0403:6015 Future Technology Devices International, Ltd Bridge(I2C/SPI/UART/FIFO)
Bus 001 Device 045: ID 0424:2517 Standard Microsystems Corp. Hub
Bus 001 Device 004: ID 0424:7800 Standard Microsystems Corp. 
Bus 001 Device 003: ID 0424:2514 Standard Microsystems Corp. USB 2.0 Hub
Bus 001 Device 002: ID 0424:2514 Standard Microsystems Corp. USB 2.0 Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

polakovic@raspi32:~/indigo $ ls -la /dev
total 4
drwxr-xr-x 15 root root        5640 Apr 14 06:22 .
drwxr-xr-x 22 root root        4096 Aug 29  2018 ..
crw-r--r--  1 root root     10, 235 Mar 17 19:17 autofs
drwxr-xr-x  2 root root         580 Mar 17 19:17 block
crw-------  1 root root     10, 234 Mar 17 19:17 btrfs-control
drwxr-xr-x  3 root root          60 Jan  1  1970 bus
crw-------  1 root root     10,  63 Mar 17 19:17 cachefiles
drwxr-xr-x  2 root root        4800 Apr 14 06:22 char
crw-------  1 root root      5,   1 Mar 17 19:36 console
crw-------  1 root root     10,  62 Mar 17 19:17 cpu_dma_latency
crw-------  1 root root     10, 203 Mar 17 19:17 cuse
drwxr-xr-x  7 root root         140 Mar 17 19:17 disk
crw-rw----  1 root video    29,   0 Mar 17 19:17 fb0
lrwxrwxrwx  1 root root          13 Nov  3  2016 fd -> /proc/self/fd
crw-rw-rw-  1 root root      1,   7 Mar 17 19:17 full
crw-rw-rw-  1 root root     10, 229 Mar 17 19:17 fuse
crw-rw----  1 root gpio    254,   0 Mar 17 19:17 gpiochip0
crw-rw----  1 root gpio    254,   1 Mar 17 19:17 gpiochip1
crw-rw----  1 root gpio    248,   0 Mar 17 19:17 gpiomem
crw-------  1 root root     10, 183 Mar 17 19:17 hwrng
lrwxrwxrwx  1 root root          25 Nov  3  2016 initctl -> /run/systemd/initctl/fifo
drwxr-xr-x  2 root root          60 Mar 31 17:47 input
crw-r--r--  1 root root      1,  11 Mar 17 19:17 kmsg
lrwxrwxrwx  1 root root          28 Nov  3  2016 log -> /run/systemd/journal/dev-log
crw-rw----  1 root disk     10, 237 Mar 17 19:17 loop-control
brw-rw----  1 root disk      7,   0 Mar 17 19:17 loop0
brw-rw----  1 root disk      7,   1 Mar 17 19:17 loop1
brw-rw----  1 root disk      7,   2 Mar 17 19:17 loop2
brw-rw----  1 root disk      7,   3 Mar 17 19:17 loop3
brw-rw----  1 root disk      7,   4 Mar 17 19:17 loop4
brw-rw----  1 root disk      7,   5 Mar 17 19:17 loop5
brw-rw----  1 root disk      7,   6 Mar 17 19:17 loop6
brw-rw----  1 root disk      7,   7 Mar 17 19:17 loop7
drwxr-xr-x  2 root root          60 Mar 17 19:17 mapper
crw-r-----  1 root kmem      1,   1 Mar 17 19:17 mem
crw-------  1 root root     10,  59 Mar 17 19:17 memory_bandwidth
brw-rw----  1 root disk    179,   0 Mar 17 19:17 mmcblk0
brw-rw----  1 root disk    179,   1 Mar 17 19:17 mmcblk0p1
brw-rw----  1 root disk    179,   2 Mar 17 19:17 mmcblk0p2
drwxrwxrwt  2 root root          40 Jan  1  1970 mqueue
drwxr-xr-x  2 root root          60 Mar 17 19:17 net
crw-------  1 root root     10,  61 Mar 17 19:17 network_latency
crw-------  1 root root     10,  60 Mar 17 19:17 network_throughput
crw-rw-rw-  1 root root      1,   3 Mar 17 19:17 null
crw-------  1 root root    108,   0 Mar 17 19:17 ppp
crw-rw-rw-  1 root tty       5,   2 Apr 14  2019 ptmx
drwxr-xr-x  2 root root           0 Nov  3  2016 pts
brw-rw----  1 root disk      1,   0 Mar 17 19:17 ram0
brw-rw----  1 root disk      1,   1 Mar 17 19:17 ram1
brw-rw----  1 root disk      1,  10 Mar 17 19:17 ram10
brw-rw----  1 root disk      1,  11 Mar 17 19:17 ram11
brw-rw----  1 root disk      1,  12 Mar 17 19:17 ram12
brw-rw----  1 root disk      1,  13 Mar 17 19:17 ram13
brw-rw----  1 root disk      1,  14 Mar 17 19:17 ram14
brw-rw----  1 root disk      1,  15 Mar 17 19:17 ram15
brw-rw----  1 root disk      1,   2 Mar 17 19:17 ram2
brw-rw----  1 root disk      1,   3 Mar 17 19:17 ram3
brw-rw----  1 root disk      1,   4 Mar 17 19:17 ram4
brw-rw----  1 root disk      1,   5 Mar 17 19:17 ram5
brw-rw----  1 root disk      1,   6 Mar 17 19:17 ram6
brw-rw----  1 root disk      1,   7 Mar 17 19:17 ram7
brw-rw----  1 root disk      1,   8 Mar 17 19:17 ram8
brw-rw----  1 root disk      1,   9 Mar 17 19:17 ram9
crw-rw-rw-  1 root root      1,   8 Mar 17 19:17 random
drwxr-xr-x  2 root root          60 Jan  1  1970 raw
crw-rw-r--  1 root netdev   10,  58 Mar 17 19:17 rfkill
drwxr-xr-x  4 root root          80 Apr 14 06:22 serial
lrwxrwxrwx  1 root root           7 Mar 17 19:17 serial1 -> ttyAMA0
drwxrwxrwt  2 root root          40 Nov  3  2016 shm
drwxr-xr-x  3 root root         160 Mar 17 19:17 snd
lrwxrwxrwx  1 root root          15 Nov  3  2016 stderr -> /proc/self/fd/2
lrwxrwxrwx  1 root root          15 Nov  3  2016 stdin -> /proc/self/fd/0
lrwxrwxrwx  1 root root          15 Nov  3  2016 stdout -> /proc/self/fd/1
crw-rw-rw-  1 root tty       5,   0 Mar 23 20:42 tty
crw--w----  1 root tty       4,   0 Mar 17 19:17 tty0
crw--w----  1 root tty       4,   1 Mar 17 19:35 tty1
crw--w----  1 root tty       4,  10 Mar 23 16:11 tty10
crw--w----  1 root tty       4,  11 Mar 23 16:11 tty11
crw--w----  1 root tty       4,  12 Mar 23 16:11 tty12
crw--w----  1 root tty       4,  13 Mar 23 16:11 tty13
crw--w----  1 root tty       4,  14 Mar 23 16:11 tty14
crw--w----  1 root tty       4,  15 Mar 23 16:11 tty15
crw--w----  1 root tty       4,  16 Mar 23 16:11 tty16
crw--w----  1 root tty       4,  17 Mar 23 16:11 tty17
crw--w----  1 root tty       4,  18 Mar 23 16:11 tty18
crw--w----  1 root tty       4,  19 Mar 23 16:11 tty19
crw--w----  1 root tty       4,   2 Mar 17 19:17 tty2
crw--w----  1 root tty       4,  20 Mar 23 16:11 tty20
crw--w----  1 root tty       4,  21 Mar 23 16:11 tty21
crw--w----  1 root tty       4,  22 Mar 23 16:11 tty22
crw--w----  1 root tty       4,  23 Mar 23 16:11 tty23
crw--w----  1 root tty       4,  24 Mar 23 16:11 tty24
crw--w----  1 root tty       4,  25 Mar 23 16:11 tty25
crw--w----  1 root tty       4,  26 Mar 23 16:11 tty26
crw--w----  1 root tty       4,  27 Mar 23 16:11 tty27
crw--w----  1 root tty       4,  28 Mar 23 16:11 tty28
crw--w----  1 root tty       4,  29 Mar 23 16:11 tty29
crw--w----  1 root tty       4,   3 Mar 17 19:17 tty3
crw--w----  1 root tty       4,  30 Mar 23 16:11 tty30
crw--w----  1 root tty       4,  31 Mar 23 16:11 tty31
crw--w----  1 root tty       4,  32 Mar 23 16:11 tty32
crw--w----  1 root tty       4,  33 Mar 23 16:11 tty33
crw--w----  1 root tty       4,  34 Mar 23 16:11 tty34
crw--w----  1 root tty       4,  35 Mar 23 16:11 tty35
crw--w----  1 root tty       4,  36 Mar 23 16:11 tty36
crw--w----  1 root tty       4,  37 Mar 23 16:11 tty37
crw--w----  1 root tty       4,  38 Mar 23 16:11 tty38
crw--w----  1 root tty       4,  39 Mar 23 16:11 tty39
crw--w----  1 root tty       4,   4 Mar 17 19:17 tty4
crw--w----  1 root tty       4,  40 Mar 23 16:11 tty40
crw--w----  1 root tty       4,  41 Mar 23 16:11 tty41
crw--w----  1 root tty       4,  42 Mar 23 16:11 tty42
crw--w----  1 root tty       4,  43 Mar 23 16:11 tty43
crw--w----  1 root tty       4,  44 Mar 23 16:11 tty44
crw--w----  1 root tty       4,  45 Mar 23 16:11 tty45
crw--w----  1 root tty       4,  46 Mar 23 16:11 tty46
crw--w----  1 root tty       4,  47 Mar 23 16:11 tty47
crw--w----  1 root tty       4,  48 Mar 23 16:11 tty48
crw--w----  1 root tty       4,  49 Mar 23 16:11 tty49
crw--w----  1 root tty       4,   5 Mar 17 19:17 tty5
crw--w----  1 root tty       4,  50 Mar 23 16:11 tty50
crw--w----  1 root tty       4,  51 Mar 23 16:11 tty51
crw--w----  1 root tty       4,  52 Mar 23 16:11 tty52
crw--w----  1 root tty       4,  53 Mar 23 16:11 tty53
crw--w----  1 root tty       4,  54 Mar 23 16:11 tty54
crw--w----  1 root tty       4,  55 Mar 23 16:11 tty55
crw--w----  1 root tty       4,  56 Mar 23 16:11 tty56
crw--w----  1 root tty       4,  57 Mar 23 16:11 tty57
crw--w----  1 root tty       4,  58 Mar 23 16:11 tty58
crw--w----  1 root tty       4,  59 Mar 23 16:11 tty59
crw--w----  1 root tty       4,   6 Mar 17 19:17 tty6
crw--w----  1 root tty       4,  60 Mar 23 16:11 tty60
crw--w----  1 root tty       4,  61 Mar 23 16:11 tty61
crw--w----  1 root tty       4,  62 Mar 23 16:11 tty62
crw--w----  1 root tty       4,  63 Mar 23 16:11 tty63
crw--w----  1 root tty       4,   7 Mar 23 16:11 tty7
crw--w----  1 root tty       4,   8 Mar 23 16:11 tty8
crw--w----  1 root tty       4,   9 Mar 23 16:11 tty9
crw-rw----  1 root dialout 204,  64 Mar 17 19:35 ttyAMA0
lrwxrwxrwx  1 root root           7 Apr 14 06:22 ttyUPB -> ttyUSB0
crw-rw-rw-  1 root dialout 188,   0 Apr 14 06:22 ttyUSB0
crw-rw----  1 root dialout 188,   1 Apr 14 06:22 ttyUSB1
crw-------  1 root root      5,   3 Mar 17 19:17 ttyprintk
crw-------  1 root root     10, 239 Mar 17 19:17 uhid
crw-------  1 root root     10, 223 Mar 17 19:17 uinput
crw-rw-rw-  1 root root      1,   9 Mar 17 19:17 urandom
crw-------  1 root root    250,   0 Mar 17 19:17 vc-mem
crw-rw----  1 root video   245,   0 Mar 17 19:17 vchiq
crw-rw----  1 root video   249,   0 Mar 17 19:17 vcio
crw-rw----  1 root tty       7,   0 Mar 17 19:17 vcs
crw-rw----  1 root tty       7,   1 Mar 17 19:17 vcs1
crw-rw----  1 root tty       7,  10 Mar 23 16:11 vcs10
crw-rw----  1 root tty       7,  11 Mar 23 16:11 vcs11
crw-rw----  1 root tty       7,  12 Mar 23 16:11 vcs12
crw-rw----  1 root tty       7,  13 Mar 23 16:11 vcs13
crw-rw----  1 root tty       7,  14 Mar 23 16:11 vcs14
crw-rw----  1 root tty       7,  15 Mar 23 16:11 vcs15
crw-rw----  1 root tty       7,  16 Mar 23 16:11 vcs16
crw-rw----  1 root tty       7,  17 Mar 23 16:11 vcs17
crw-rw----  1 root tty       7,  18 Mar 23 16:11 vcs18
crw-rw----  1 root tty       7,  19 Mar 23 16:11 vcs19
crw-rw----  1 root tty       7,   2 Mar 17 19:17 vcs2
crw-rw----  1 root tty       7,  20 Mar 23 16:11 vcs20
crw-rw----  1 root tty       7,  21 Mar 23 16:11 vcs21
crw-rw----  1 root tty       7,  22 Mar 23 16:11 vcs22
crw-rw----  1 root tty       7,  23 Mar 23 16:11 vcs23
crw-rw----  1 root tty       7,  24 Mar 23 16:11 vcs24
crw-rw----  1 root tty       7,  25 Mar 23 16:11 vcs25
crw-rw----  1 root tty       7,  26 Mar 23 16:11 vcs26
crw-rw----  1 root tty       7,  27 Mar 23 16:11 vcs27
crw-rw----  1 root tty       7,  28 Mar 23 16:11 vcs28
crw-rw----  1 root tty       7,  29 Mar 23 16:11 vcs29
crw-rw----  1 root tty       7,   3 Mar 17 19:17 vcs3
crw-rw----  1 root tty       7,  30 Mar 23 16:11 vcs30
crw-rw----  1 root tty       7,  31 Mar 23 16:11 vcs31
crw-rw----  1 root tty       7,  32 Mar 23 16:11 vcs32
crw-rw----  1 root tty       7,  33 Mar 23 16:11 vcs33
crw-rw----  1 root tty       7,  34 Mar 23 16:11 vcs34
crw-rw----  1 root tty       7,  35 Mar 23 16:11 vcs35
crw-rw----  1 root tty       7,  36 Mar 23 16:11 vcs36
crw-rw----  1 root tty       7,  37 Mar 23 16:11 vcs37
crw-rw----  1 root tty       7,  38 Mar 23 16:11 vcs38
crw-rw----  1 root tty       7,  39 Mar 23 16:11 vcs39
crw-rw----  1 root tty       7,   4 Mar 17 19:17 vcs4
crw-rw----  1 root tty       7,  40 Mar 23 16:11 vcs40
crw-rw----  1 root tty       7,  41 Mar 23 16:11 vcs41
crw-rw----  1 root tty       7,  42 Mar 23 16:11 vcs42
crw-rw----  1 root tty       7,  43 Mar 23 16:11 vcs43
crw-rw----  1 root tty       7,  44 Mar 23 16:11 vcs44
crw-rw----  1 root tty       7,  45 Mar 23 16:11 vcs45
crw-rw----  1 root tty       7,  46 Mar 23 16:11 vcs46
crw-rw----  1 root tty       7,  47 Mar 23 16:11 vcs47
crw-rw----  1 root tty       7,  48 Mar 23 16:11 vcs48
crw-rw----  1 root tty       7,  49 Mar 23 16:11 vcs49
crw-rw----  1 root tty       7,   5 Mar 17 19:17 vcs5
crw-rw----  1 root tty       7,  50 Mar 23 16:11 vcs50
crw-rw----  1 root tty       7,  51 Mar 23 16:11 vcs51
crw-rw----  1 root tty       7,  52 Mar 23 16:11 vcs52
crw-rw----  1 root tty       7,  53 Mar 23 16:11 vcs53
crw-rw----  1 root tty       7,  54 Mar 23 16:11 vcs54
crw-rw----  1 root tty       7,  55 Mar 23 16:11 vcs55
crw-rw----  1 root tty       7,  56 Mar 23 16:11 vcs56
crw-rw----  1 root tty       7,  57 Mar 23 16:11 vcs57
crw-rw----  1 root tty       7,  58 Mar 23 16:11 vcs58
crw-rw----  1 root tty       7,  59 Mar 23 16:11 vcs59
crw-rw----  1 root tty       7,   6 Mar 17 19:17 vcs6
crw-rw----  1 root tty       7,  60 Mar 23 16:11 vcs60
crw-rw----  1 root tty       7,  61 Mar 23 16:11 vcs61
crw-rw----  1 root tty       7,  62 Mar 23 16:11 vcs62
crw-rw----  1 root tty       7,  63 Mar 23 16:11 vcs63
crw-rw----  1 root tty       7,   7 Mar 23 16:11 vcs7
crw-rw----  1 root tty       7,   8 Mar 23 16:11 vcs8
crw-rw----  1 root tty       7,   9 Mar 23 16:11 vcs9
crw-rw----  1 root tty       7, 128 Mar 17 19:17 vcsa
crw-rw----  1 root tty       7, 129 Mar 17 19:17 vcsa1
crw-rw----  1 root tty       7, 138 Mar 23 16:11 vcsa10
crw-rw----  1 root tty       7, 139 Mar 23 16:11 vcsa11
crw-rw----  1 root tty       7, 140 Mar 23 16:11 vcsa12
crw-rw----  1 root tty       7, 141 Mar 23 16:11 vcsa13
crw-rw----  1 root tty       7, 142 Mar 23 16:11 vcsa14
crw-rw----  1 root tty       7, 143 Mar 23 16:11 vcsa15
crw-rw----  1 root tty       7, 144 Mar 23 16:11 vcsa16
crw-rw----  1 root tty       7, 145 Mar 23 16:11 vcsa17
crw-rw----  1 root tty       7, 146 Mar 23 16:11 vcsa18
crw-rw----  1 root tty       7, 147 Mar 23 16:11 vcsa19
crw-rw----  1 root tty       7, 130 Mar 17 19:17 vcsa2
crw-rw----  1 root tty       7, 148 Mar 23 16:11 vcsa20
crw-rw----  1 root tty       7, 149 Mar 23 16:11 vcsa21
crw-rw----  1 root tty       7, 150 Mar 23 16:11 vcsa22
crw-rw----  1 root tty       7, 151 Mar 23 16:11 vcsa23
crw-rw----  1 root tty       7, 152 Mar 23 16:11 vcsa24
crw-rw----  1 root tty       7, 153 Mar 23 16:11 vcsa25
crw-rw----  1 root tty       7, 154 Mar 23 16:11 vcsa26
crw-rw----  1 root tty       7, 155 Mar 23 16:11 vcsa27
crw-rw----  1 root tty       7, 156 Mar 23 16:11 vcsa28
crw-rw----  1 root tty       7, 157 Mar 23 16:11 vcsa29
crw-rw----  1 root tty       7, 131 Mar 17 19:17 vcsa3
crw-rw----  1 root tty       7, 158 Mar 23 16:11 vcsa30
crw-rw----  1 root tty       7, 159 Mar 23 16:11 vcsa31
crw-rw----  1 root tty       7, 160 Mar 23 16:11 vcsa32
crw-rw----  1 root tty       7, 161 Mar 23 16:11 vcsa33
crw-rw----  1 root tty       7, 162 Mar 23 16:11 vcsa34
crw-rw----  1 root tty       7, 163 Mar 23 16:11 vcsa35
crw-rw----  1 root tty       7, 164 Mar 23 16:11 vcsa36
crw-rw----  1 root tty       7, 165 Mar 23 16:11 vcsa37
crw-rw----  1 root tty       7, 166 Mar 23 16:11 vcsa38
crw-rw----  1 root tty       7, 167 Mar 23 16:11 vcsa39
crw-rw----  1 root tty       7, 132 Mar 17 19:17 vcsa4
crw-rw----  1 root tty       7, 168 Mar 23 16:11 vcsa40
crw-rw----  1 root tty       7, 169 Mar 23 16:11 vcsa41
crw-rw----  1 root tty       7, 170 Mar 23 16:11 vcsa42
crw-rw----  1 root tty       7, 171 Mar 23 16:11 vcsa43
crw-rw----  1 root tty       7, 172 Mar 23 16:11 vcsa44
crw-rw----  1 root tty       7, 173 Mar 23 16:11 vcsa45
crw-rw----  1 root tty       7, 174 Mar 23 16:11 vcsa46
crw-rw----  1 root tty       7, 175 Mar 23 16:11 vcsa47
crw-rw----  1 root tty       7, 176 Mar 23 16:11 vcsa48
crw-rw----  1 root tty       7, 177 Mar 23 16:11 vcsa49
crw-rw----  1 root tty       7, 133 Mar 17 19:17 vcsa5
crw-rw----  1 root tty       7, 178 Mar 23 16:11 vcsa50
crw-rw----  1 root tty       7, 179 Mar 23 16:11 vcsa51
crw-rw----  1 root tty       7, 180 Mar 23 16:11 vcsa52
crw-rw----  1 root tty       7, 181 Mar 23 16:11 vcsa53
crw-rw----  1 root tty       7, 182 Mar 23 16:11 vcsa54
crw-rw----  1 root tty       7, 183 Mar 23 16:11 vcsa55
crw-rw----  1 root tty       7, 184 Mar 23 16:11 vcsa56
crw-rw----  1 root tty       7, 185 Mar 23 16:11 vcsa57
crw-rw----  1 root tty       7, 186 Mar 23 16:11 vcsa58
crw-rw----  1 root tty       7, 187 Mar 23 16:11 vcsa59
crw-rw----  1 root tty       7, 134 Mar 17 19:17 vcsa6
crw-rw----  1 root tty       7, 188 Mar 23 16:11 vcsa60
crw-rw----  1 root tty       7, 189 Mar 23 16:11 vcsa61
crw-rw----  1 root tty       7, 190 Mar 23 16:11 vcsa62
crw-rw----  1 root tty       7, 191 Mar 23 16:11 vcsa63
crw-rw----  1 root tty       7, 135 Mar 23 16:11 vcsa7
crw-rw----  1 root tty       7, 136 Mar 23 16:11 vcsa8
crw-rw----  1 root tty       7, 137 Mar 23 16:11 vcsa9
crw-rw----  1 root video   246,   0 Mar 17 19:17 vcsm
crw-------  1 root root     10, 137 Mar 17 19:17 vhci
crw-------  1 root root     10, 130 Mar 17 19:17 watchdog
crw-------  1 root root    252,   0 Mar 17 19:17 watchdog0
crw-rw-rw-  1 root root      1,   5 Mar 17 19:17 zero

polakovic@raspi32:~/indigo $ ls -al /dev/serial/by-id
total 0
drwxr-xr-x 2 root root 80 Apr 14 06:22 .
drwxr-xr-x 4 root root 80 Apr 14 06:22 ..
lrwxrwxrwx 1 root root 13 Apr 14 06:22 usb-Pegasus_Astro_UPB_v1.7_PA36T4RB-if00-port0 -> ../../ttyUSB0
lrwxrwxrwx 1 root root 13 Apr 14 06:22 usb-Prolific_Technology_Inc._USB-Serial_Controller-if00-port0 -> ../../ttyUSB1

06:24:54.741483 indigo_server: INDIGO Bus: property definition
06:24:54.741675 indigo_server: 'Mount SynScan'.'DEVICE_PORTS' SWITCH rw Ok 2.0 OneOfMany { // Serial ports
06:24:54.741863 indigo_server:   'REFRESH' = Off // Refresh
06:24:54.742048 indigo_server:   '/dev/ttyUSB1' = Off // /dev/ttyUSB1
06:24:54.742136 indigo_server:   '/dev/serial1' = Off // /dev/serial1
06:24:54.742390 indigo_server:   '/dev/ttyAMA0' = Off // /dev/ttyAMA0
06:24:54.742970 indigo_server:   '/dev/ttyUSB1' = Off // /dev/ttyUSB1
06:24:54.743025 indigo_server:   '/dev/ttyUSB0' = Off // /dev/ttyUSB0
06:24:54.743363 indigo_server: }

**Comment by polakovic** [comment]
What I suppose to see is /dev/ttyUSB0 and /dev/ttyUSB1, but also /dev/ttyUPB (preselected by UPB driver)!

**Comment by rumengb** [comment]
Created workaround, Pegasus is not seen by the OS as a real UART. Confirmed to work.
