### ISSUE TITLE
Compatibility issue with Stellarium over INDI driver

### ISSUE THREAD

**Issue by polakovic** [indigo-astronomy/indigo#206]

**Comment by rumengb** [comment]
Alex Wolf the stellarium maintainer tested it:
Александр, 18:29
I've tried today connect to INDIGO Server through Stellarium/INDI client - it works without problem (after unparking mount in INDIGO Control Panel)

maybe you should unpark first?

**Comment by rumengb** [comment]
![image](https://user-images.githubusercontent.com/20597893/71886348-b7d5ca00-3144-11ea-89ae-9379c28771b3.png)
 Everything works. The only issue is that the telescope should be unremarked first. but this is stellarium issue.
