### ISSUE TITLE
location of libjpeg.a

### ISSUE THREAD

**Issue by DerPit** [indigo-astronomy/indigo#21]
Just did a git clone and make, as suggested in the readme.  Linking libindigo.so fails because it cannot find libjpeg.a:
gcc -shared -o build/lib/libindigo.so indigo_libs/indigo_xml.o  .......
gcc: error: build/lib/libjpeg.a: No such file or directory
make: *** [Makefile:532: build/lib/libindigo.so] Error 1

The previous install steps have actually installed the library in build/lib64/libjpeg.a

This is an openSUSE Tumbleweed 20180626

(I had also missed installing gphoto2-devel; the configure steps seemed not to have cought this, so the above step also fails with a missing -lgphoto2)

**Comment by rumengb** [comment]
This is supposed t be fixed with commit b99d12b019121c0d5857a9eadc6dc7e9619485a9
:)
