### ISSUE TITLE
EQ8 support in SynScan driver

### ISSUE THREAD

**Issue by polakovic** [indigo-astronomy/indigo#211]
Missing support for encoders (nice to have) and home indexer (a must to setup the mount).

**Comment by JohanBakk** [comment]
Just to make sure i won't be forgotten; the AZ-EQ6 had encoders as well.. :-)

**Comment by polakovic** [comment]
Yep, we know and working on it just now. But AZ-EQ6 can be used without this fix, EQ8 can't :(

**Comment by polakovic** [comment]
Example code for autohoming is here: https://stargazerslounge.com/topic/238364-eq8-tools-autohome-without-handset/

**Comment by polakovic** [comment]
Encoders & PPEC support is added: 0c9acf540f9d3769f98d6fb2634750bbe87c25ce
Home index support is pending...

**Comment by polakovic** [comment]
done: 6013a5bea79c9aec9e0222eb7ae5ec3a309947a9
