### ISSUE TITLE
On send message device name is empty

### ISSUE THREAD

**Issue by rumengb** [indigo-astronomy/indigo#216]
16:09:40.094 Device: **@ localhost**: [ERROR] Telescope coordinates missing. Make sure telescope is connected and its name is set in CCD Options.

 `<message device="**CCD Simulator**" timestamp="2019-07-02T12:17:45" message="[ERROR] Telescope coordinates missing. Make sure telescope is connected and its name is set in CCD Options."/>
`
even if the device host suffix is turned off the suffix is still shown...
Maybe it is replaced not added?

**Comment by polakovic** [comment]
Fixed
