### ISSUE TITLE
Reference to s_rpi_ctrl.sh in indigo_server.c

### ISSUE THREAD

**Issue by asantam** [indigo-astronomy/indigo#231]
Hi,
In [indigo_server.c](https://github.com/indigo-astronomy/indigo/blob/master/indigo_server/indigo_server.c) there are several references to a non-existing file **s_rpi_ctrl.sh** (which were added in https://github.com/indigo-astronomy/indigo/commit/8401dee5ca132c40a83a3c8d7ae6e44fb39c0a13). Should this actually be referring to [rpi_ctrl.sh](https://github.com/indigo-astronomy/indigo/blob/master/tools/rpi_ctrl.sh) or is **s_rpi_ctrl.sh** planned to be added in the future?

Best wishes,
Andres

**Comment by polakovic** [comment]
These scripts are used to control INDIGO Sky (to set time, wifi mode, upgrade, reboot, etc.) and s_rpi_ctrl.sh is not present in general distribution. You can find it here if you're interested:

https://github.com/indigo-astronomy/pi-gen/tree/master/stage2-indigo/05-install-scripts/files

Peter
