### ISSUE TITLE
Feature Request: eqmod mount driver

### ISSUE THREAD

**Issue by ghulands** [indigo-astronomy/indigo#268]
It'd be great to support eqmod based mounts in indigo.

**Comment by ghulands** [comment]
I saw the skywatcher mounts are in the synscan driver. Does this require the hand controller to be plugged in or can it connect direct to the usb port on the mount? I'm planing on an EQ8-Rh Pro.

**Comment by rumengb** [comment]
Synscan driver is basically Eqmod. It can be used with HC in pc direct mode
or without hc with a dedicated cable.

Rumen.

**Comment by ghulands** [comment]
Thanks for the info
