### ISSUE TITLE
Why does the mount agent have LX200 stuff in it?

### ISSUE THREAD

**Issue by ghulands** [indigo-astronomy/indigo#273]
Hi,
I found it a little confusing why the mount agent has the two LX200 sections in it?

![image](https://user-images.githubusercontent.com/127462/72127388-553b2480-3324-11ea-89b7-e53f722e81d1.png)

As you can see I don't have the LX200 mount selected.
![image](https://user-images.githubusercontent.com/127462/72127414-73a12000-3324-11ea-96f4-a0805464b3d7.png)

Is this a bug?

**Comment by rumengb** [comment]
Hi, a lot of the existing software can speak Lx200 protocol out of the box.
Got that reason nount agent can accept lx200 and translate it to Indigo and
pass it to the native driver. This way every lx200 capable software can
control every mount.

**Comment by ghulands** [comment]
Thanks for the explanation.
