### ISSUE TITLE
Deep Sky Dad AF3

### ISSUE THREAD

**Issue by polakovic** [indigo-astronomy/indigo#280]
It needs baudrate property to be enabled.

https://aptforum.com/phpbb/viewtopic.php?f=27&t=3153&sid=0eaedf149ee8bb0a02de8fe8e2c2d799

**Comment by rumengb** [comment]
It is not only baud rate. Dsd af3 is a bit different. I will add support for it soon.

**Comment by rumengb** [comment]
All fixed but untested!
