### ISSUE TITLE
indigo_ccd_ptp: Cannot connect SONY a7SII

### ISSUE THREAD

**Issue by tail-feather** [indigo-astronomy/indigo#290]
SONY a7SII cannot be connected without commenting out `libusb_set_configuration` in ptp_open.
(But there is no need to commenting out `libusb_clear_halt`.)

refs: https://github.com/indigo-astronomy/indigo/issues/276

**Comment by polakovic** [comment]
All in one solution! :)

**Comment by tail-feather** [comment]
Fixed by #291
