### ISSUE TITLE
"&" Not allowed in property description 

### ISSUE THREAD

**Issue by rumengb** [indigo-astronomy/indigo#297]
This works:
indigo_init_switch_item(LA_DOME_FUNCTION_2_BUTTONS_ITEM, LA_DOME_FUNCTION_2_BUTTONS_ITEM_NAME, "2 Buttons, push **and** hold (#1-Open, #2-Close)", false);

This  freezes the framewrk:
indigo_init_switch_item(LA_DOME_FUNCTION_2_BUTTONS_ITEM, LA_DOME_FUNCTION_2_BUTTONS_ITEM_NAME, "2 Buttons, push **&** hold (#1-Open, #2-Close)", false);

**Comment by polakovic** [comment]
4fe3e5d38d53b2a8b3531e4798dc4a5c5cee40d0

**Comment by rumengb** [comment]
This does not fix the issue. it is the same.

**Comment by polakovic** [comment]
c3bb7ee9b88f08be1838d0a4830fc7bf2e3d64e7
