### ISSUE TITLE
cg usb-st4 driiver locks the bus on connect and never times out if there is no device

### ISSUE THREAD

**Issue by rumengb** [indigo-astronomy/indigo#307]

**Comment by rumengb** [comment]
This actually affects all serial devices on indigosky. 
I can not reproduce it on intel Linux and Mac.

How to reproduce:
1. Select existing serial port where nothing is connected.
2. Connect.
3. The property goes busy waiting on read() which never times out.

As this is done in change_property() the whole INDIGO bus i blocked.

**Comment by polakovic** [comment]
Hm, so timeout setting doesn't work on arm?

**Comment by rumengb** [comment]
yes but only with the internal serial ports... strange!

**Comment by rumengb** [comment]
RPi uses internal serial port as a console by default. if you disable it everything is fine!
