### ISSUE TITLE
Please add manual filter wheel or filter drawer

### ISSUE THREAD

**Issue by tlkw79** [indigo-astronomy/indigo#312]
Hi,

Please add manual filter wheel or filter drawer. Thanks

**Comment by rumengb** [comment]
Hi,
i am not sure I understand, how can this be controlled by the computer if it is manual?

Rumen

**Comment by polakovic** [comment]
I do, the reason is to copy filter name metadata to fits files. It is on my TODO list, but not implemented yet.

**Comment by rumengb** [comment]
In that case wheel simulator can be used isn't it? at least untill we have dedicated drover for that. It should be easy to implement...

**Comment by polakovic** [comment]
Yes, you're right. Simulator can do the job.

**Comment by rumengb** [comment]
Created! Will this do the job?

![image](https://user-images.githubusercontent.com/20597893/80693698-15b76480-8adc-11ea-8c2e-07b4876bd6da.png)

**Comment by tlkw79** [comment]
how and where I can get it?

**Comment by rumengb** [comment]
It will be in the next Indigo release.
