### ISSUE TITLE
ASIAIR aux device ?

### ISSUE THREAD

**Issue by astrorafael** [indigo-astronomy/indigo#334]
ASIAIR is an interesting device. It is a bit more than a RPi4 in disguise. It has a HAT to control four 12V power outputs that are independently switchable. Are there any plans to include an `aux_asiair` device in your indigosky distribution?
Best wishes
Rafael

**Comment by rumengb** [comment]
I doubt ASI will be happy with this. ASIAIR is a proprietary product which
sells fith their own image and they will not be happy to share the
specification of this HAT. But we can try...

**Comment by astrorafael** [comment]
Thanks ! let's cross fingers ...

**Comment by rumengb** [comment]
Can you contact me in personal at rumen@skyarchive.org

**Comment by astrorafael** [comment]
Sure! mail sent

**Comment by rumengb** [comment]
Discussed with ZWO and they prefer not to make such integration. So this can not be done!
