### ISSUE TITLE
Driver UPBv2: does not connect in first attempt

### ISSUE THREAD

**Issue by Ruediger3** [indigo-astronomy/indigo#336]
Hello Rumen and Peter,
when connecting UPBv2 the first connect attempt fails. It needs a second try to establish connection.
If it was connected and disconnected you can connect immediately. 

Version 120 installed via apt.

Logfile:
16:25:30.427548 indigo_server: indigo_aux_upb[aux_connection_handler:758, 0x744fb3d0]: UPB not detected
16:25:30.428634 indigo_server: indigo_aux_upb[aux_connection_handler:951, 0x744fb3d0]: Failed to connect to /dev/ttyUPB

**Comment by rumengb** [comment]
Peter, please see what I did in mgpbox driver. Maybe the problem is the same. The device fails to respond to commands when freshly booted and needs several attempts with some delay in between...

**Comment by Ruediger3** [comment]
The UPBv2 was not booted in between. Just the INDIGO server was restarting.

**Comment by polakovic** [comment]
Pls. can you check if it works now? Thank you!

**Comment by Ruediger3** [comment]
Hi Peter,sure I will test asap. Only need some good weather. The equipment is in the house because of very bad weather here. 
I will update this issue.

**Comment by Ruediger3** [comment]
Hi Peter,
 just tested and INDIGO connected on the first attempt. 
Thanks for fixing! Enjoy your weekend!
Cheers
Rüdiger
