### ISSUE TITLE
Driver MGBox: Connect causes restart of server

### ISSUE THREAD

**Issue by Ruediger3** [indigo-astronomy/indigo#337]
Hello Rumen and Peter,

I have loaded driver indigo_aux_mgbox.so in V120. When I try to connect MGBox the server restarts.

Logfile:
/usr/bin/indigo_worker: symbol lookup error: /usr/bin/../lib/../lib/indigo_aux_mgbox.so: undefined symbol: indigo_cancel_timer_sync

Thank you!

**Comment by rumengb** [comment]
This is behaviour is expected and it is not a bug. This driver uses a call introduced in 2.0.121 framework. Seems like you are trying to load it in Indigo 2.0.120. Please use the driver with indigo 2.0.121...

**Comment by Ruediger3** [comment]
😊 but not available via apt-get 😝

 

Cheers

Rüdiger

 

 

Von: Rumen Bogdanovski <notifications@github.com> 
Gesendet: Samstag, 23. Mai 2020 23:26
An: indigo-astronomy/indigo <indigo@noreply.github.com>
Cc: Ruediger3 <r.proske@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [indigo-astronomy/indigo] Driver MGBox: Connect causes restart of server (#337)

 

This is behaviour is expected and it is not a bug. This driver uses a call introduced in 2.0.121 framework. Seems like you are trying to load it in Indigo 2.0.120. Please use the driver with indigo 2.0.121...

**Comment by rumengb** [comment]
You can use it with the version of Indigo you  compiled it. It will fail to compile against 2.0.120 anyway...

**Comment by Ruediger3** [comment]
Not possible. DEV System is not in productive environment. P-System is installed via APT only.
