### ISSUE TITLE
Web App for Mount control does not update connected state properly

### ISSUE THREAD

**Issue by ozbandit** [indigo-astronomy/indigo#361]
If I plug in a serial port USB dongle and configure synscan mount to use that serial port, but there is no mount actually connected, if I ask the mount driver to connect, it tries to detect the mount, fails, and auto-disconnects. However, the web UI continues to indicate connected state and appears to ignore attempts to manually disconnect (because it already is disconnected).

Reproducible on indigo sky and Mac using latest git repo.

**Comment by polakovic** [comment]
Fixed in 4411e35b90d2e25ebf8527bca67b4c045d74f2d9
