### ISSUE TITLE
ccd_simultor: coolding does not work

### ISSUE THREAD

**Issue by rumengb** [indigo-astronomy/indigo#383]
![image](https://user-images.githubusercontent.com/20597893/97677035-49c70e80-1a9a-11eb-8fcb-1405af2ee9a3.png)
turn on cooling set target temperate and nothing happens.

**Comment by polakovic** [comment]
It does work :) Temperature is decreased or increased 1 degree every 5 seconds/

**Comment by rumengb** [comment]
It just does not work sometimes. I waited for several minutes. Then
reloaded the diver.

**Comment by rumengb** [comment]
It is not only the cooler. When i start guiding with guider imager, start exposures with imager and turn the temperature control on. very often it never starts, sometimes guider freezes like in the example below:

rumen@vega:~/work/indigo_deadlock_detector.git$ ./indigo_deadlock_detector.sh indigo_server
Inspecting 'indigo_server' (pid = 363067) for deadlocks
[New LWP 363068]
[New LWP 363069]
[New LWP 363070]
[New LWP 363071]
[New LWP 363072]
[New LWP 363076]
[New LWP 363078]
[New LWP 363079]
[New LWP 363080]
[New LWP 363081]
[New LWP 363103]
[New LWP 363117]
[New LWP 363143]
[New LWP 363286]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007f2861e8849f in __libc_accept (fd=9, addr=..., addr@entry=..., len=len@entry=0x7ffe95a4b3e4) at ../sysdeps/unix/sysv/linux/accept.c:26
None

Thread 15 (Thread 0x7f283f7fe700 (LWP 363286)):
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7f2830001874) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x7f2830001878, cond=0x7f2830001848) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=cond@entry=0x7f2830001848, mutex=mutex@entry=0x7f2830001878) at pthread_cond_wait.c:638
#3  0x00007f2861ebe99b in timer_func (timer=0x7f2830001820) at indigo_timer.c:123
#4  0x00007f2861e7d609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#5  0x00007f2861da4293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 14 (Thread 0x7f283ffff700 (LWP 363143)):
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7f2838005994) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x7f2838005998, cond=0x7f2838005968) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=cond@entry=0x7f2838005968, mutex=mutex@entry=0x7f2838005998) at pthread_cond_wait.c:638
#3  0x00007f2861ebe99b in timer_func (timer=0x7f2838005940) at indigo_timer.c:123
#4  0x00007f2861e7d609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#5  0x00007f2861da4293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 13 (Thread 0x7f2851ffb700 (LWP 363117)):
#0  futex_abstimed_wait_cancelable (private=<optimized out>, abstime=0x7f2851ffae20, clockid=<optimized out>, expected=0, futex_word=0x7f2844000bb0) at ../sysdeps/nptl/futex-internal.h:320
#1  __pthread_cond_wait_common (abstime=0x7f2851ffae20, clockid=<optimized out>, mutex=0x7f2844000bb8, cond=0x7f2844000b88) at pthread_cond_wait.c:520
#2  __pthread_cond_timedwait (cond=cond@entry=0x7f2844000b88, mutex=mutex@entry=0x7f2844000bb8, abstime=abstime@entry=0x7f2851ffae20) at pthread_cond_wait.c:656
#3  0x00007f2861ebea76 in timer_func (timer=0x7f2844000b60) at indigo_timer.c:74
#4  0x00007f2861e7d609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#5  0x00007f2861da4293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 12 (Thread 0x7f28517fa700 (LWP 363103)):
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7f2848023f64) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x7f2848023f68, cond=0x7f2848023f38) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=cond@entry=0x7f2848023f38, mutex=mutex@entry=0x7f2848023f68) at pthread_cond_wait.c:638
#3  0x00007f2861ebe99b in timer_func (timer=0x7f2848023f10) at indigo_timer.c:123
#4  0x00007f2861e7d609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#5  0x00007f2861da4293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 11 (Thread 0x7f28527fc700 (LWP 363081)):
#0  0x00007f2861d623bf in __GI___clock_nanosleep (clock_id=clock_id@entry=0, flags=flags@entry=0, req=req@entry=0x7f28527fbd40, rem=rem@entry=0x0) at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:78
#1  0x00007f2861d68047 in __GI___nanosleep (requested_time=requested_time@entry=0x7f28527fbd40, remaining=remaining@entry=0x0) at nanosleep.c:27
#2  0x00007f2861d9a9bf in usleep (useconds=<optimized out>) at ../sysdeps/posix/usleep.c:32
#3  0x00007f2861eca77e in indigo_usleep (delay=<optimized out>) at indigo_bus.c:1314
#4  0x00007f2862d6025f in exposure_batch (device=device@entry=0x7f285413ab30) at indigo_agent_imager.c:426
#5  0x00007f2862d606e1 in exposure_batch_process (device=0x7f285413ab30) at indigo_agent_imager.c:525
#6  0x00007f2861ebe8a8 in timer_func (timer=0x7f2848024de0) at indigo_timer.c:86
#7  0x00007f2861e7d609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#8  0x00007f2861da4293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 10 (Thread 0x7f2852ffd700 (LWP 363080)):
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7f2848024c20) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x7f2848024c28, cond=0x7f2848024bf8) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=cond@entry=0x7f2848024bf8, mutex=mutex@entry=0x7f2848024c28) at pthread_cond_wait.c:638
#3  0x00007f2861ebe99b in timer_func (timer=0x7f2848024bd0) at indigo_timer.c:123
#4  0x00007f2861e7d609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#5  0x00007f2861da4293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 9 (Thread 0x7f28537fe700 (LWP 363079)):
#0  0x00007f2861d623bf in __GI___clock_nanosleep (clock_id=clock_id@entry=0, flags=flags@entry=0, req=req@entry=0x7f28537fdc40, rem=rem@entry=0x0) at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:78
#1  0x00007f2861d68047 in __GI___nanosleep (requested_time=requested_time@entry=0x7f28537fdc40, remaining=remaining@entry=0x0) at nanosleep.c:27
#2  0x00007f2861d9a9bf in usleep (useconds=useconds@entry=10000) at ../sysdeps/posix/usleep.c:32
#3  0x00007f2861eca77e in indigo_usleep (delay=delay@entry=10000) at indigo_bus.c:1314
#4  0x00007f286081a489 in capture_raw_frame (device=device@entry=0x7f2854333550) at indigo_agent_guider.c:206
#5  0x00007f286081e6ba in guide_and_capture_frame (ra=0, dec=<optimized out>, device=0x7f2854333550) at indigo_agent_guider.c:502
#6  guide_and_capture_frame (dec=<optimized out>, ra=0, device=0x7f2854333550) at indigo_agent_guider.c:498
#7  _calibrate_process (device=0x7f2854333550, will_guide=<optimized out>) at indigo_agent_guider.c:635
#8  0x00007f2861ebe8a8 in timer_func (timer=0x7f2848000b60) at indigo_timer.c:86
#9  0x00007f2861e7d609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#10 0x00007f2861da4293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 8 (Thread 0x7f2853fff700 (LWP 363078)):
#0  futex_abstimed_wait_cancelable (private=<optimized out>, abstime=0x7f2853ffee20, clockid=<optimized out>, expected=0, futex_word=0x7f28544e5df0) at ../sysdeps/nptl/futex-internal.h:320
#1  __pthread_cond_wait_common (abstime=0x7f2853ffee20, clockid=<optimized out>, mutex=0x7f28544e5df8, cond=0x7f28544e5dc8) at pthread_cond_wait.c:520
#2  __pthread_cond_timedwait (cond=cond@entry=0x7f28544e5dc8, mutex=mutex@entry=0x7f28544e5df8, abstime=abstime@entry=0x7f2853ffee20) at pthread_cond_wait.c:656
#3  0x00007f2861ebea76 in timer_func (timer=0x7f28544e5da0) at indigo_timer.c:74
#4  0x00007f2861e7d609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#5  0x00007f2861da4293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 7 (Thread 0x7f2858e47700 (LWP 363076)):
#0  __libc_read (nbytes=524288, buf=0x7f284c000ce0, fd=21) at ../sysdeps/unix/sysv/linux/read.c:26
#1  __libc_read (fd=fd@entry=21, buf=buf@entry=0x7f284c000ce0, nbytes=nbytes@entry=524288) at ../sysdeps/unix/sysv/linux/read.c:24
#2  0x00007f2861edf967 in read (__nbytes=524288, __buf=0x7f284c000ce0, __fd=21) at /usr/include/x86_64-linux-gnu/bits/unistd.h:44
#3  indigo_xml_parse (device=device@entry=0x0, client=client@entry=0x7f284c000b60) at indigo_xml.c:1277
#4  0x00007f2861ebc885 in start_worker_thread (client_socket=0x563885b97e80) at indigo_server_tcp.c:96
#5  0x00007f2861e7d609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#6  0x00007f2861da4293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 6 (Thread 0x7f2859648700 (LWP 363072)):
#0  __libc_read (nbytes=524288, buf=0x7f2854000ce0, fd=20) at ../sysdeps/unix/sysv/linux/read.c:26
#1  __libc_read (fd=fd@entry=20, buf=buf@entry=0x7f2854000ce0, nbytes=nbytes@entry=524288) at ../sysdeps/unix/sysv/linux/read.c:24
#2  0x00007f2861edf967 in read (__nbytes=524288, __buf=0x7f2854000ce0, __fd=20) at /usr/include/x86_64-linux-gnu/bits/unistd.h:44
#3  indigo_xml_parse (device=device@entry=0x0, client=client@entry=0x7f2854000b60) at indigo_xml.c:1277
#4  0x00007f2861ebc885 in start_worker_thread (client_socket=0x563885b97e40) at indigo_server_tcp.c:96
#5  0x00007f2861e7d609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#6  0x00007f2861da4293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 5 (Thread 0x7f2859e49700 (LWP 363071)):
#0  __libc_read (nbytes=1, buf=0x7f2859e48dcf, fd=15) at ../sysdeps/unix/sysv/linux/read.c:26
#1  __libc_read (fd=15, buf=0x7f2859e48dcf, nbytes=1) at ../sysdeps/unix/sysv/linux/read.c:24
#2  0x00007f2862d32037 in ?? () from /lib/x86_64-linux-gnu/libdns_sd.so.1
#3  0x00007f2862d32172 in ?? () from /lib/x86_64-linux-gnu/libdns_sd.so.1
#4  0x00007f2861e7d609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#5  0x00007f2861da4293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 4 (Thread 0x7f285a64a700 (LWP 363070)):
#0  __libc_read (nbytes=1, buf=0x7f285a649dcf, fd=10) at ../sysdeps/unix/sysv/linux/read.c:26
#1  __libc_read (fd=10, buf=0x7f285a649dcf, nbytes=1) at ../sysdeps/unix/sysv/linux/read.c:24
#2  0x00007f2862d32037 in ?? () from /lib/x86_64-linux-gnu/libdns_sd.so.1
#3  0x00007f2862d32172 in ?? () from /lib/x86_64-linux-gnu/libdns_sd.so.1
#4  0x00007f2861e7d609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#5  0x00007f2861da4293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7f2861024700 (LWP 363069)):
#0  0x00007f2861d97aff in __GI___poll (fds=0x7f285c000b60, nfds=2, timeout=60000) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f2861afe40d in ?? () from /lib/x86_64-linux-gnu/libusb-1.0.so.0
#2  0x00007f2861aff65c in libusb_handle_events_timeout_completed () from /lib/x86_64-linux-gnu/libusb-1.0.so.0
#3  0x00007f2861aff6b3 in libusb_handle_events () from /lib/x86_64-linux-gnu/libusb-1.0.so.0
#4  0x00007f2861ecba17 in hotplug_thread (arg=<optimized out>) at indigo_driver.c:613
#5  0x00007f2861e7d609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#6  0x00007f2861da4293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7f2861825700 (LWP 363068)):
#0  0x00007f2861d97aff in __GI___poll (fds=0x7f2861824e40, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f2861b051a2 in ?? () from /lib/x86_64-linux-gnu/libusb-1.0.so.0
#2  0x00007f2861e7d609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#3  0x00007f2861da4293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7f2861829600 (LWP 363067)):
#0  0x00007f2861e8849f in __libc_accept (fd=9, addr=..., addr@entry=..., len=len@entry=0x7ffe95a4b3e4) at ../sysdeps/unix/sysv/linux/accept.c:26
#1  0x00007f2861ebb1f1 in indigo_server_start (callback=<optimized out>) at indigo_server_tcp.c:378
#2  0x000056388562cd4d in server_main () at indigo_server.c:1154
#3  0x000056388562aea5 in main (argc=<optimized out>, argv=<optimized out>) at indigo_server.c:1296

Blocked threads:
*****************************************************
*****************************************************

[Inferior 1 (process 363067) detached]

And the exposure becomes busy... and stays like that forever:
![image](https://user-images.githubusercontent.com/20597893/97765600-68211e80-1b1b-11eb-907e-76433c35d15b.png)

**Comment by rumengb** [comment]
it is not new.... it affects 2.0-128 too on both rpi and intel

**Comment by polakovic** [comment]
fixed by 6850e5cbd88f076acde4440724a5d5869df1e057
