### ISSUE TITLE
[RFC] display longitude as -180 .. +180?

### ISSUE THREAD

**Issue by ckuethe** [indigo-astronomy/indigo#394]
Any chance of switching the display of longitude to -180..+180? That would match the +/-90 degree range of latitude. 235 degrees east doesn't mean much to me whereas -125 degrees (or 125W) does. I didn't see anything in the UI that would allow me to adjust the display. On the contrary, I see a few places where longitude is normalized to 0-360, eg.

* https://github.com/indigo-astronomy/indigo/blob/master/indigo_drivers/gps_gpsd/externals/libgps/gps.h#L85
* https://github.com/indigo-astronomy/indigo/blob/master/indigo_libs/indigo_mount_driver.c#L494

**Comment by polakovic** [comment]
I would like it too, but we can't change it, it will break compatibility with legacy INDI clients :(

https://indilib.org/develop/developer-manual/101-standard-properties.html#h2-general

INDIGO accepts -180...360 range, but normalise it to 0...360. Nevertheless, you're right, that it can be presented in -180...180 range in webGUI. I'll look at it later.
