### ISSUE TITLE
【【ONSTEP】】could you add ONSTEP to indigo_server driver

### ISSUE THREAD

**Issue by acseyang** [indigo-astronomy/indigo#395]
ONSTEP is a common lx200 mount driver,it also have indi driver,could you add it to indigo_server.

**Comment by acseyang** [comment]
https://www.indilib.org/media/kunena/attachments/3515/OnStep_Indi_Driver_Doc.pdf

**Comment by acseyang** [comment]
https://github.com/indilib/indi/tree/master/drivers/telescope


it have   LX200_onstep  and  teenAstro   TWO  version

**Comment by polakovic** [comment]
ONSTEP is supported by LX200 driver already and is detected automatically.
