### ISSUE TITLE
Svbony SV305 or SV305 pro camera

### ISSUE THREAD

**Issue by tlkw79** [indigo-astronomy/indigo#397]
Hi,

Is there a plan to support this camera soon?

Thanks
Tom

**Comment by rumengb** [comment]
Not really :(
I tried to get the SDK for that camera but it is not available for linux and mac. We do not have the hardware so we need to write the driver blindly and hope that somebody will test and report back. this is a long process and it can not happen in the next several weeks or month. So I will add it in the TODO list, contact Svbony about the sdk and we will see. This is all I can promise now.

**Comment by polakovic** [comment]
I'm in contact with Svbony already. They promised linux/macOS SDK couple of times during last year or two, but I don't expect they will do it.

**Comment by tlkw79** [comment]
Here you are.....

https://www.mediafire.com/file/ugd0j3m7i8t9z0f/macos_SV305Pro_SVBCameraSDK_v1.2.5.tar.gz/file

https://www.mediafire.com/file/ehsov9wzsvlrlqj/SDK1.2.5-1119.zip/file

**Comment by polakovic** [comment]
Tom, do you know where is that code from? There is no license, no documentation and no technical or business contact inside.

@rumengb the header file is identical to header file of ZWO ASI SDK. If the library has also identical behaviour, it may be easy. What puzzles me is, that INDI has completely different driver for it.

**Comment by tlkw79** [comment]
All these SDK files are from Svbony.  

For INDI, someone re-write the whole driver for SV305 but not for SV305 pro.

**Comment by polakovic** [comment]
I'll try to clone ZWO ASI driver and we'll see.

**Comment by polakovic** [comment]
Hm, ARM6 libraries are missing. SDK used by INDI-3rdparty contains only dynamic libraries and we need static :(

**Comment by polakovic** [comment]
So it is not so easy :( It is a clone of some ZWO ASI SDK, but of some very old one. Different content of data structures and different function signatures. This can't be debugged without an access to the camera...

**Comment by tlkw79** [comment]
ok. Will close this as well since INDI already successfully supports it well. Thanks.
