### ISSUE TITLE
How I can build INDIGO in Manjaro (Arch Linux)

### ISSUE THREAD

**Issue by shepard127** [indigo-astronomy/indigo#405]
The method described in the Readme does not work.

[make_info.txt](https://github.com/indigo-astronomy/indigo/files/6335751/make_info.txt)

_and then console output:
autoreconf: export WARNINGS=
autoreconf: Entering directory '.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
configure.ac:23: error: AC_CONFIG_MACRO_DIR can only be used once
./lib/autoconf/general.m4:1970: AC_CONFIG_MACRO_DIR is expanded from...
configure.ac:23: the top level
autom4te: error: /usr/bin/m4 failed with exit status: 1
aclocal: error: /usr/bin/autom4te failed with exit status: 1
autoreconf: error: aclocal failed with exit status: 1
/bin/sh: строка 1: ./configure: Нет такого файла или каталога
make[2]: *** Не заданы цели и не найден make-файл.  Останов.
make[2]: *** Нет правила для сборки цели «install».  Останов.
make[1]: *** [Makefile:161: /home/shepard127/Soft/indigo/build/lib/libhidapi-hidraw.a] Ошибка 2
make: *** [Makefile:144: all] Error 2_

**Comment by rumengb** [comment]
Hi,
you have to find the names of the packages needed to compile it on manjaro
and install them. We provide only Ubuntu, Debian and Fedora lists. And
actually only debian and ubuntu derivatives are really supported. The
Fedora howto is quite dated.  If you provide the full build log we may be
able to help.
But I recommend checking all dependencies and find their names on Manjaro
and install them.

Rumen
