### ISSUE TITLE
Can't set gain in web imager

### ISSUE THREAD

**Issue by ckuethe** [indigo-astronomy/indigo#416]
Kind of related to indigo-astronomy/indigo_imager#6 - I can enable streaming preview in the web ui but I can't change camera gain.

Trace log: https://gist.github.com/6e0bb6b55f8e0e343fc1b7b5c73622df
![Screenshot_2021-11-17_11-10-06](https://user-images.githubusercontent.com/1131751/142268211-47462b5c-4c1a-41d9-b3ea-20ad1c56b3c4.png)

(Don't worry about the noisy image; I'm taking darks for this sensor)

**Comment by rumengb** [comment]
Web Imager is supposed to provide only basic functionality and not a complete imaging solution. However you can change every single property from the web GUI, just go to "Control panel" tab then Imager Agent-> Camera -> Gain:
![image](https://user-images.githubusercontent.com/20597893/142278559-98c8839a-97cf-4baf-81a5-bb9ab847efe3.png)

**Comment by ckuethe** [comment]
Yes, I use the control panel tab a lot - I just thought it would be helpful to have that that relatively basic control in the imager tab.
