### ISSUE TITLE
Client force server setting to update image to the client

### ISSUE THREAD

**Issue by Ghir8** [indigo-astronomy/indigo#463]
Hi,
we are using INDIGO to command a dome remotely, it would be nice if the images could be saved into the (in loco) server for backup and to avoid loosing them by some internet hiccups.
We select the "Upload and save" and we save the configuration but when we select the camera in the client program (Ain) the setting is overwrite to "Upload to client".

Is this a bug or an intended behavior? How can we force the desired behavior?
Thanks a lot!

**Comment by rumengb** [comment]
Ain forces images to be downloaded to the client as it is not yet ready to work in client less environment. I need to solve several problems before I can make Ain to work in this setup.

**Comment by Ghir8** [comment]
Thank you for the replay! 
Ok, we will wait for future Ain update then :)

**Comment by rumengb** [comment]
Released!
