### ISSUE TITLE
Image Transfer Method - agent_alpaca

### ISSUE THREAD

**Issue by BobDenny** [indigo-astronomy/indigo#471]
I noticed this on the [alpaca_bridge README](https://github.com/indigo-astronomy/indigo/blob/master/indigo_drivers/agent_alpaca/README.md) under [Selecting "Image array transfer transfer method"](https://github.com/indigo-astronomy/indigo/blob/master/indigo_drivers/agent_alpaca/README.md#selecting-image-array-transfer-transfer-method).  In 2019, the new [ImageBytes image transfer method](https://ascom-standards.org/Developer/AlpacaImageBytes.pdf) was introduced and was made a standard part of ASCOM Platform 6.6 in January 2022 (a year ago not just now). You might want to revise the README to select ImageBytes as the preferred method. We're hoping those older transfer schemes will simply go away.  All of the COM and Alpaca bits, the Alpaca Omni Simulator, and the Conforn Universal tools, as well as the Python Alpyca package use ImageBytes by default. 

Also if there is anything we can do to help with, or make provisions for, cross-compatibility between INDI and Alpaca, please engage at the [ASCOM Driver and Application Development Support Forum](https://ascomtalk.groups.io/g/Developer) on Groups.io.

**Comment by polakovic** [comment]
Yep, README is outdated and we have to update it. ImageBytes transfer mode is already implemented.

> Also if there is anything we can do to help with, or make provisions for, cross-compatibility between INDI and Alpaca, please engage at the [ASCOM Driver and Application Development Support Forum](https://ascomtalk.groups.io/g/Developer) on Groups.io.

As far as this is Alpaca Bridge is an INDIGO agent, it will never work with INDI, just with INDIGO.

**Comment by polakovic** [comment]
README updated...

**Comment by BobDenny** [comment]
Peter — Thanks very much for the fast response!! If there is something that we can do  to  make this easier or better please feel free to ask on the ASCOM Developer Forum at https://ascomtalk.groups.io/g/Developer
