### ISSUE TITLE
LX200 - Support OpenAstroTech mounts

### ISSUE THREAD

**Issue by jimtjames** [indigo-astronomy/indigo#491]
The current LX200 driver does not support [OpenAstroTech](https://wiki.openastrotech.com/) mounts. These mounts have an LX200-like serial protocol documented [here](https://wiki.openastrotech.com/Knowledge/Firmware/MeadeCommands).

Some key differences are a 19200 baudrate and extra properties for add-ons (GPS, level, etc.).  I've started work on supporting this mount on  [this fork](https://github.com/jimtjames/indigo/tree/openastrotech_lx200), mostly just using the Meade flavor of commands with a 19200 baudrate.

**Comment by polakovic** [comment]
I’ll look at it.

**Comment by jimtjames** [comment]
Great, thank you! The fork I wrote is able to connect to the mount and move it in Ain, though I haven't tested it much beyond that.
