### ISSUE TITLE
Mount Simulator/Mount Synscan : park position stuck at north pole

### ISSUE THREAD

**Issue by wgoltz** [indigo-astronomy/indigo#507]
I am in the southern hemisphere.

With the Mount Agent, there doesn't appear to be any way to get the Mount Simulator to park at the south pole. Also the hour angle of Home position is always 6 hrs and can't be changed.

Using Synscan, the park position on startup (unparked) appears to correctly showing the south pole but pressing park button in Mount Agent tries to send the scope to the north pole (not nice!). Changing the park position dec to +90 in Synscan appears to correctly park the scope (at -90). This is not a good fix.

Attempting slew from park position (but unparked) using map click in Mount Agent does not work.

Without using Mount Agent, parking also parks at north pole when park point is set to south pole.

**Comment by rumengb** [comment]
When you set the latitude to a negative number as shown below:
[image: image.png]
The park position will automatically change to -90 degrees as shown below:
[image: image.png]
Also, you can enter custom Park Position here.
If you want to preserve this settings you need to go to: [Mount name] ->
Main ->Profile selection and select Profile #0

[image: image.png]
Then select Configuration Control as shown below and click on Save:
[image: image.png]
This way the park position will be preserved for this mount
hope this helps!

**Comment by rumengb** [comment]
What driver are you using?

**Comment by wgoltz** [comment]
I have been experimenting with the Mount Simulator, Mount SynScan and Mount Nexstar and the Mount Agent with a Skywatcher AZeq5.

I am using the web interface and Skychart (Carte du Ciel) and gcx programs (my version of gcx is on github). I run indigo_server on a remote Pi controlling the telescope and I have indigo_server running on my laptop which just provides mousepad support. Skychart I run on the laptop, gcx I run on the Pi as it gives better performance running there. It is all connected together over WiFi using the home broadband modem.

I have been having problems with the Pi freezing or at least running very slowly. This problem with parking is the first definite error that seems to be related to indigo.

**Comment by wgoltz** [comment]
Simplest way to reproduce problem for me: Starting with telescope at home position (some hour angle, -90) but unparked (what you get with AZeq5 after starting at home position). Initialize indigo by restarting server, connect nexstar mount, load nexstar configuration, check nexstar mount position displays (0, -90), it does. Now select park button in nexstar mount - the telescope heads of to the north pole!

**Comment by rumengb** [comment]
I have checked the Mount simulator and the Nexstar driver with my AZ-EQ6 mount. 
1. mount simulator - yes there is a bug in the simulator - it always starts fron +90degrees regardless of the latitude - I will fix it.
2. Nexstar - no I can not reproduce the problem. But I see what you are missing. Setting the  park position is not preserved between the sessions. To make it permanent choose "[mount name] -> Main -> Profile selection -> Profile #0" as shown:

![image](https://github.com/indigo-astronomy/indigo/assets/20597893/d41733e4-df65-46c0-ab1b-779d6d668b12)

then save current configuration with  "[mount name] -> Configuration Control -> Save"

![image](https://github.com/indigo-astronomy/indigo/assets/20597893/a032b1ef-b5ad-49cd-8c36-2a61b605822d)

if saved to profile #0 it will be auto-loaded at start.

This way your park position will be made permanent and toy can enter whatever HA and Dec you like.

**Comment by wgoltz** [comment]
Using the browser interface and Mount Nexstar, profile #0 is NOT loaded automatically and the park position shows as (6, 90). When I manually click load in Configuration Control the position shows correctly (0, -90). Perhaps auto-loading does not always work correctly with the browser interface? I have been confused before not knowing whether profiles have been loaded, not just with Mount Nexstar.

**Comment by rumengb** [comment]
Sorry, it is my bad. it is autoloaded by the mount agent. So you need to load the configuration manually if you are not using it through the agent.

**Comment by wgoltz** [comment]
Using the agent, the park position shows as (0, 90) when the manually loaded park position was (0, -90).

**Comment by rumengb** [comment]
Just checked it and it works:
![image](https://github.com/indigo-astronomy/indigo/assets/20597893/21102cab-6984-4fe0-a828-353594c259c2)
you need to select the mount from the mount list as shown above.

**Comment by wgoltz** [comment]
When everything starts up fresh, the Mount Agent consistently shows (0, 90) (north pole) as the current coords . Mount Nexstar and the display on the controller both agree they are pointing at the south pole, though they slightly differ. I can slew to a nearby star. The coords in Mount Agent agree much the same as coords on the controller, difference in epoch between the two? Check park position in Mount Nexstar (0, -90), good. Click park button in Mount Agent - off to north pole again!

Same result as reported earlier.

**Comment by wgoltz** [comment]
It looks like I might have been editing options without loading presets first. My changes get saved back with other default options which are wrong.

I can get SynScan to park at south pole. There is still a problem with SynScan home/park positions - the home hour angle always returns to 6hrs and the park position is off by 6hrs to what I select.

Nexstar still goes to the north pole when parked.

As an aside, the Pi got stuck with the Mount Agent sky display drifting whilst I was playing with SynScan options. Response improved when cable to mount was disconnected. I am not sure whether the cable should be directly connected to the mount or through the synscan controller. It seems both ways work, but the direct connection was immediately slower and coincided with the Pi getting stuck (maybe just coincidental).

**Comment by wgoltz** [comment]
There is no MOUNT_HOME_POSITION saved to ~/.indigo/SynScan.config so it cannot be restored from there (if that is the way it is supposed to work).

Checking for something similar with Nexstar, I reset the actual telescope and the server, started from park and slewed to a nearby star. When I switched from Mount Agent to Mount Nexstar the equatorial coords got zeroed out somehow. Restarted server and the coords were ok again. Tried a park and the telescope looked like it was headed to the south pole ... but no - it went straight though and off to the north pole again.

I haven't had any success getting the log file to work. I deleted the existing log file at /home/indigo/indigo.log but it hasn't reappeared.

**Comment by rumengb** [comment]
I will try to reproduce it.

**Comment by wgoltz** [comment]
I have sorted out the log files. Turning on Debug in log levels and using Nexstar the log shows:

indigo_mount_nexstar[mount_handle_park:445]: Going to park position: HA = 0.00000 Dec = -90.00000

before it then goes and parks at the north pole.

When it is parked correctly, the synscan controller internal axes always show as (0, 90), but I expect that is irrelevent.

**Comment by rumengb** [comment]
Yes, you are right MOUNT_HOME_POSITION was not saved. I have fixed it in git. Most likely nobody ever changed home position. Probably, because the home position is nonchangeable and is a fixed position marked by a sensor. Skywatcher and Celestron are one of these. For these mounts, there is also no park position supported by the protocol and it is also emulated by the driver.

**Comment by wgoltz** [comment]
Great! A fix. 

I never actually use the park through indigo as there was obviously a problem the first time I tried. I always use the controller. That is not operator free, which is what (any sane, armchair astronomer) is aiming for.
