### ISSUE TITLE
PEC with SynScan Mount and AZeq5

### ISSUE THREAD

**Issue by wgoltz** [indigo-astronomy/indigo#508]
From my readings, the AZeq6 has hardware PEC and the AZeq5 has software PEC. Does indigo not provide PEC control of AZeq5 as it is software PEC, even though the synscan device is emulated?

My trials suggest it doesn't. There are no PEC files generated after a PEC training run, and no change to the drive performance when PEC is enabled.

My RA drive has full periodic error of 90 arcsec, and with image scale at 1.6 arcsec/pl, my maximum exposure is 10 seconds. I don't want to add a guide scope and controller at the moment, so I definitely need functioning PEC.

**Comment by rumengb** [comment]
Then you may need to get another mount :)
There are very few mounts on the market that can track without guiding even with PEC.
INDIGO Does not support PEC.
