### ISSUE TITLE
Crash out w/Touptek Camera

### ISSUE THREAD

**Issue by AlexLee24** [indigo-astronomy/indigo#514]
**MacOS 14.2.1 (Intel)**
INDIGO crashed out with the Touptek 2600 camera while using 16bit to capture.
![image](https://github.com/indigo-astronomy/indigo/assets/104354570/ed6d8c71-3564-43e9-a5d0-98d36bcd8ab5)
But when I used 8bit to capture it was all good, nothing happened.

Here is the crash log from Apple.
[INDIGO_D1-2023-12-23-Toup.txt](https://github.com/indigo-astronomy/indigo/files/13762079/INDIGO_D1-2023-12-23-Toup.txt)

**Comment by rumengb** [comment]
It should be fixed can you try with the latest version
