### ISSUE TITLE
Support Touptek filter wheel 

### ISSUE THREAD

**Issue by rohan5sep** [indigo-astronomy/indigo#521]
It is already supported in indi via 3rd party libraries.

https://github.com/indilib/indi-3rdparty/tree/master/indi-toupbase

Usage: indiserver -v indi_toupcam_wheel

I have purchased the filter wheel and would like to use it in indigo. Is there any way to load this driver in indigo server? I can even test the driver code if required.

**Comment by rumengb** [comment]
it is supported by the indigo camera driver. please wait a couple of days
for the release.
