### ISSUE TITLE
Image format set to "Raw data" despite "FITS format" was previously selected

### ISSUE THREAD

**Issue by Paolo97Gll** [indigo-astronomy/indigo#526]
Hello, I have a problem with the image format. Sometimes - I can't tell you from when, but months for sure - INDIGO switches to "Raw data" image format, despite I set "FITS format": this cause INDIGO to save entire batches in Raw and not in FITS.

![image](https://github.com/indigo-astronomy/indigo/assets/49845775/12297ee7-7d61-4be0-90e2-275d6753367d)

Today, I noticed that INDIGO, when using the autofocus with subframe enabled, switches to "Raw data" image format. However, when the autofocus procedure stops (due both to fail or success), the image format doesn't reset to "FITS format" and remains in "Raw format".

I haven't run extensive testing, but can this be the source of the problem?

**Comment by rumengb** [comment]
Fixed with commit a9bd95833abc7cb29ab13e73907a272433ce5764
