### ISSUE TITLE
PegasusAstro FocusCube 3

### ISSUE THREAD

**Issue by chrsoo** [indigo-astronomy/indigo#530]
The PegasusAstro Focuser DMFC driver indicates support for...

- PegasusAstro Motor Focus Kit
- PegasusAstro FocusCube
- PegasusAstro FocusCube 2

Doing due diligence for potential purchase.

[FocusCube 2 is now discontinued](https://pegasusastro.com/products/focuscube-2-universal/) and replaced by [FocusCube 3](https://pegasusastro.com/products/focuscube-3-universal/).

Does anybody know if the newer FocusCube 3 is also supported?

If not, any plans of supporting it in the near future?

**Comment by polakovic** [comment]
I doubt it will work out of box, but it should be easy to add FC3 support. I'll ask Pegasus for protocol description.

**Comment by polakovic** [comment]
Evangelos promised to send documents once they return from NEAF24 (around 24 April).

**Comment by chrsoo** [comment]
@polakovic - any news from Evangelos / PegasusAstro?

**Comment by polakovic** [comment]
Not yet :( I'll try to ping Evans again...

**Comment by polakovic** [comment]
Still nothing, I pinged him again today...

**Comment by polakovic** [comment]
Hopefully done, I had to make new driver for FocusCube3+ devices, because the protocol is substantially different:

https://github.com/indigo-astronomy/indigo/tree/master/indigo_drivers/focuser_focuscube
