### ISSUE TITLE
multi-columns bloom sx ccd

### ISSUE THREAD

**Issue by fcbarclo** [indigo-astronomy/indigo#532]
Using Starlight Oculus Pro 180 all sky camera , on a raspberry pi 4 8gb ram, ssd disk, and bullseye os. Latest version of indigo; using indigo_ccd_sx driver.
During day it shows multi-columns bloom on the area overexposed. It seems that using the driver indigo_ccd_sx it is not possibile to go under 0.0001 seconds of exposure. 
The multi-columns like this:
![attach_1](https://github.com/indigo-astronomy/indigo/assets/26539791/ee06d88e-1a68-4abe-b227-8499825caf97)

increases during day , up to completely fill the image like this:
![attach_3](https://github.com/indigo-astronomy/indigo/assets/26539791/a9b2b6db-c0e3-4afd-aa16-71bcf5c0242e)

I know that camera has a fixed gain. But, is it possible to implement a way lower minimal exposure time of 0.0001 ?

**Comment by polakovic** [comment]
I checked the driver and it looks that SX cameras have just millisecond resolution, so shorted exposure time is not possible :(
