### ISSUE TITLE
indigo_focuser_moonlite driver missing

### ISSUE THREAD

**Issue by emogg** [indigo-astronomy/indigo#71]
I understand that moonlite is untested, but it is not included in your build for INDIGO for ARM64 (V8) Debian Linux: indigo-2.0-73-arm64.deb. Is this an oversight, or am I missing something. I'm using indigo for my ZWO camera, and that works very well.

**Comment by polakovic** [comment]
Hi, yes, it is not included in "production" packages yet. But if you have physical hardware and can help with testing, I'll make binaries for you tonight. Can you send me e-mail message to info@cloudmakers.eu? Peter

**Comment by polakovic** [comment]
Added to 2.0-74 packages.
